/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Login_Daftar_Recovery;

import MainMenu_Dashboard_Bantuan.MenuUtama;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author acer_
 */
public class FormMasuk extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin
     */
    public FormMasuk() {
        initComponents();
        
        jTextField1.setBackground(new Color(0,0,0,0));
        pass.setBackground(new Color(0,0,0,0));
        username.setBackground(new Color (0,0,0,0));
        jTextField2.setBackground(new Color (0,0,0,0));
        
        //signup
        id.setBackground(new Color(0,0,0,0));
        latarid.setBackground(new Color(0,0,0,0));
        recoverycode.setBackground(new Color(0,0,0,0));
        latarrecovery.setBackground(new Color(0,0,0,0));
        lataruser.setBackground(new Color(0,0,0,0));
        signupPass.setBackground(new Color(0,0,0,0));
        signupUser.setBackground(new Color (0,0,0,0));
        latarpass.setBackground(new Color (0,0,0,0));
        
        PanelSignup.setVisible(false);
        panelPilihan.setVisible(false);
    }
    
    //
        Connection Connect = DatabaseConnect.DatabaseConnect.getKoneksi("localhost", "3306", "root", "", "database_ooptugasakhir");
        ClassAkun1 ca = new ClassAkun1();
   
    private void close(JFrame form){
        form.dispose();
    }    
        
    public void changecolor (JPanel panel, Color warna) {
        panel.setBackground(warna);
    }
    
    public void changeCtext (JLabel txt, Color warna) {
        txt.setForeground(warna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        taskbar = new javax.swing.JPanel();
        iconPanel = new javax.swing.JPanel();
        jpclose = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpmax = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpmin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        pSignup = new javax.swing.JPanel();
        txtsignup = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbutton = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        ButtonLogIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        PanelSignup = new javax.swing.JPanel();
        recoverycode = new javax.swing.JTextField();
        latarrecovery = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        latarid = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        plogin = new javax.swing.JPanel();
        txtLogin = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        signupUser = new javax.swing.JTextField();
        lataruser = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        signupPass = new javax.swing.JPasswordField();
        latarpass = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        showpadd = new javax.swing.JToggleButton();
        txtnama = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        panelPilihan = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        karyawan = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        supplier = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/loginPic.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        taskbar.setBackground(new java.awt.Color(67, 119, 169));
        taskbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconPanel.setBackground(new java.awt.Color(67, 119, 169));
        iconPanel.setPreferredSize(new java.awt.Dimension(138, 25));
        iconPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpclose.setBackground(new java.awt.Color(27, 35, 42));
        jpclose.setPreferredSize(new java.awt.Dimension(35, 35));
        jpclose.setLayout(new java.awt.BorderLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/closeToolbar3.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jpclose.add(jLabel10, java.awt.BorderLayout.CENTER);

        iconPanel.add(jpclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 50, 25));

        jpmax.setBackground(new java.awt.Color(67, 119, 169));
        jpmax.setPreferredSize(new java.awt.Dimension(35, 35));
        jpmax.setLayout(new java.awt.BorderLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/maxToolBar.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jpmax.add(jLabel9, java.awt.BorderLayout.CENTER);

        iconPanel.add(jpmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 25));

        jpmin.setBackground(new java.awt.Color(67, 119, 169));
        jpmin.setPreferredSize(new java.awt.Dimension(35, 35));
        jpmin.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/minToolBar2.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jpmin.add(jLabel8, java.awt.BorderLayout.CENTER);

        iconPanel.add(jpmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 25));

        taskbar.add(iconPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 0, -1, 32));

        jPanel1.add(taskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 32));

        PanelLogin.setBackground(new java.awt.Color(255, 255, 255));
        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pSignup.setBackground(new java.awt.Color(27, 35, 42));
        pSignup.setLayout(new java.awt.BorderLayout());

        txtsignup.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtsignup.setForeground(new java.awt.Color(255, 255, 255));
        txtsignup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtsignup.setText("Sign up");
        txtsignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtsignupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtsignupMouseExited(evt);
            }
        });
        pSignup.add(txtsignup, java.awt.BorderLayout.CENTER);

        PanelLogin.add(pSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 73, 27));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Welcome Back");
        PanelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, 40));

        txtbutton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtbutton.setText("Forgot your password ?");
        txtbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtbuttonMousePressed(evt);
            }
        });
        PanelLogin.add(txtbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 150, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Email or Username");
        PanelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 20));

        username.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        username.setCaretColor(new java.awt.Color(255, 255, 255));
        username.setOpaque(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });
        PanelLogin.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 280, 30));

        jTextField1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Username");
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextField1.setEnabled(false);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        PanelLogin.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 280, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Password");
        PanelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 20));

        pass.setBackground(new java.awt.Color(51, 51, 51));
        pass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setBorder(null);
        pass.setOpaque(false);
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passKeyTyped(evt);
            }
        });
        PanelLogin.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, 30));

        jTextField2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Password");
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextField2.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextField2.setEnabled(false);
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        PanelLogin.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, 30));

        ButtonLogIn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ButtonLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/loginField1.png"))); // NOI18N
        ButtonLogIn.setBorder(null);
        ButtonLogIn.setBorderPainted(false);
        ButtonLogIn.setContentAreaFilled(false);
        ButtonLogIn.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/loginField2.png"))); // NOI18N
        ButtonLogIn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/loginField2.png"))); // NOI18N
        ButtonLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogInActionPerformed(evt);
            }
        });
        ButtonLogIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ButtonLogInKeyTyped(evt);
            }
        });
        PanelLogin.add(ButtonLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 290, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/textfield.png"))); // NOI18N
        PanelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/textfield.png"))); // NOI18N
        PanelLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 290, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Show");
        PanelLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, 20));

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/hidepass1.png"))); // NOI18N
        jToggleButton1.setBorder(null);
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.setContentAreaFilled(false);
        jToggleButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/hidepass1.png"))); // NOI18N
        jToggleButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/showpass1.png"))); // NOI18N
        jToggleButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/showpass1.png"))); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        PanelLogin.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 30, 20));

        jPanel1.add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 32, 360, 478));

        PanelSignup.setBackground(new java.awt.Color(255, 255, 255));
        PanelSignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recoverycode.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        recoverycode.setForeground(new java.awt.Color(255, 255, 255));
        recoverycode.setBorder(null);
        recoverycode.setCaretColor(new java.awt.Color(255, 255, 255));
        recoverycode.setOpaque(false);
        recoverycode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recoverycodeActionPerformed(evt);
            }
        });
        recoverycode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                recoverycodeKeyTyped(evt);
            }
        });
        PanelSignup.add(recoverycode, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, 30));

        latarrecovery.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        latarrecovery.setForeground(new java.awt.Color(255, 255, 255));
        latarrecovery.setText("Recovery code");
        latarrecovery.setBorder(null);
        latarrecovery.setCaretColor(new java.awt.Color(255, 255, 255));
        latarrecovery.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        latarrecovery.setEnabled(false);
        latarrecovery.setOpaque(false);
        latarrecovery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latarrecoveryActionPerformed(evt);
            }
        });
        PanelSignup.add(latarrecovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 280, 30));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/textfield.png"))); // NOI18N
        PanelSignup.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 290, 30));

        id.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setBorder(null);
        id.setCaretColor(new java.awt.Color(255, 255, 255));
        id.setOpaque(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        PanelSignup.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("id");
        PanelSignup.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 100, 20));

        latarid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        latarid.setForeground(new java.awt.Color(255, 255, 255));
        latarid.setText("id");
        latarid.setBorder(null);
        latarid.setCaretColor(new java.awt.Color(255, 255, 255));
        latarid.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        latarid.setEnabled(false);
        latarid.setOpaque(false);
        latarid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lataridActionPerformed(evt);
            }
        });
        PanelSignup.add(latarid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 100, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/textfield.png"))); // NOI18N
        PanelSignup.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        plogin.setBackground(new java.awt.Color(27, 35, 42));
        plogin.setLayout(new java.awt.BorderLayout());

        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(255, 255, 255));
        txtLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogin.setText("Log in");
        txtLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtLoginMouseExited(evt);
            }
        });
        plogin.add(txtLogin, java.awt.BorderLayout.CENTER);

        PanelSignup.add(plogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 73, 27));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel23.setText("Create your account now here");
        PanelSignup.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Sign up");
        PanelSignup.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 180, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Username");
        PanelSignup.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, 20));

        signupUser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        signupUser.setForeground(new java.awt.Color(255, 255, 255));
        signupUser.setBorder(null);
        signupUser.setCaretColor(new java.awt.Color(255, 255, 255));
        signupUser.setOpaque(false);
        signupUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupUserActionPerformed(evt);
            }
        });
        signupUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                signupUserKeyTyped(evt);
            }
        });
        PanelSignup.add(signupUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 280, 30));

        lataruser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        lataruser.setForeground(new java.awt.Color(255, 255, 255));
        lataruser.setText("Username");
        lataruser.setBorder(null);
        lataruser.setCaretColor(new java.awt.Color(255, 255, 255));
        lataruser.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        lataruser.setEnabled(false);
        lataruser.setOpaque(false);
        lataruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lataruserActionPerformed(evt);
            }
        });
        PanelSignup.add(lataruser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 280, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Password");
        PanelSignup.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 20));

        signupPass.setBackground(new java.awt.Color(51, 51, 51));
        signupPass.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        signupPass.setForeground(new java.awt.Color(255, 255, 255));
        signupPass.setBorder(null);
        signupPass.setOpaque(false);
        signupPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                signupPassKeyTyped(evt);
            }
        });
        PanelSignup.add(signupPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, 30));

        latarpass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        latarpass.setForeground(new java.awt.Color(255, 255, 255));
        latarpass.setText("Password");
        latarpass.setBorder(null);
        latarpass.setCaretColor(new java.awt.Color(255, 255, 255));
        latarpass.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        latarpass.setEnabled(false);
        latarpass.setOpaque(false);
        latarpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latarpassActionPerformed(evt);
            }
        });
        PanelSignup.add(latarpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, 30));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/createField.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/createField1.png"))); // NOI18N
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/createField1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton4KeyTyped(evt);
            }
        });
        PanelSignup.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 290, 30));

        jCheckBox3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jCheckBox3.setText("Term& Conditions");
        jCheckBox3.setOpaque(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        PanelSignup.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/textfield.png"))); // NOI18N
        PanelSignup.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/textfield.png"))); // NOI18N
        PanelSignup.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 290, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Show");
        PanelSignup.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, 20));

        showpadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/hidepass1.png"))); // NOI18N
        showpadd.setBorder(null);
        showpadd.setBorderPainted(false);
        showpadd.setContentAreaFilled(false);
        showpadd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/hidepass1.png"))); // NOI18N
        showpadd.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/showpass1.png"))); // NOI18N
        showpadd.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/showpass1.png"))); // NOI18N
        showpadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpaddActionPerformed(evt);
            }
        });
        PanelSignup.add(showpadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 30, 20));

        txtnama.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtnama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtnama.setText("Nama Anda");
        txtnama.setEnabled(false);
        PanelSignup.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 100, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/cariicon.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        PanelSignup.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 60, 30));

        jPanel1.add(PanelSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 32, 360, 478));

        panelPilihan.setBackground(new java.awt.Color(0, 0, 0));
        panelPilihan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Hey! Let's get you started");
        panelPilihan.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        karyawan.setBackground(new java.awt.Color(27, 35, 42));
        karyawan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("For Employee");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        karyawan.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Data akun pengguna bagi karyawan");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });
        karyawan.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 30));

        panelPilihan.add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 240, 70));

        supplier.setBackground(new java.awt.Color(27, 35, 42));
        supplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("For Supplier");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel20MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel20MouseExited(evt);
            }
        });
        supplier.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Supplier");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });
        supplier.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Data akun Business check data bagi");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        supplier.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 190, 20));

        panelPilihan.add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 240, 90));

        jPanel1.add(panelPilihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 360, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
       if (jToggleButton1.isSelected()) {
           pass.setEchoChar((char)0);
       }else {
           pass.setEchoChar('*');
       }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ButtonLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogInActionPerformed
        String inputuser = username.getText();
        String inputpass = pass.getText();
        
        FormMasuk form = new FormMasuk();
        
        ca.LoginAkun(inputuser, inputpass, form, this);
        
    }//GEN-LAST:event_ButtonLogInActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        
    }//GEN-LAST:event_usernameActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        if ("".equals(username.getText()))
        {
            jTextField1.setVisible(true);
            jTextField1.setEnabled(false);
             
        }else {
            jTextField1.setVisible(false);
            jTextField1.setEnabled(false);
        }
        
    }//GEN-LAST:event_usernameKeyTyped

    private void passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyTyped
        if ("".equals(pass.getText()))
        {
            jTextField2.setVisible(true);
            jTextField2.setEnabled(false);
        }else {
            jTextField2.setVisible(false);
            jTextField2.setEnabled(false);
        }
        
    }//GEN-LAST:event_passKeyTyped

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        changecolor(jpclose, new Color(234, 44, 12));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void ButtonLogInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtonLogInKeyTyped
       
    }//GEN-LAST:event_ButtonLogInKeyTyped

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        changecolor(jpclose, new Color(27,35,42));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        changecolor(jpmin, new Color(54, 101, 179));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
       changecolor(jpmin, new Color (67, 119, 169));
    }//GEN-LAST:event_jLabel8MouseExited

    private void signupUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupUserActionPerformed

    private void signupUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupUserKeyTyped
        if ("".equals(signupUser.getText())){
            lataruser.setEnabled(false);
            lataruser.setVisible(true);
        }else {
            lataruser.setEnabled(false);
            lataruser.setVisible(false);
        }
    }//GEN-LAST:event_signupUserKeyTyped

    private void lataruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lataruserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lataruserActionPerformed

    private void signupPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_signupPassKeyTyped
        if ("".equals(signupPass.getText())){
            latarpass.setVisible(true);
            latarpass.setEnabled(false);
        }else {
            latarpass.setEnabled(false);
            latarpass.setVisible(false);
        }
    }//GEN-LAST:event_signupPassKeyTyped

    private void latarpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latarpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latarpassActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jCheckBox3.isSelected()){
            String idtxt = id.getText();
            String usertxt = signupUser.getText();
            String passtxt = signupPass.getText();
            String sctxt = recoverycode.getText();
            ca.daftarakun(idtxt, usertxt, passtxt, sctxt);
        }else {
            JOptionPane.showMessageDialog(this, "Please check term&condition");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4KeyTyped

    private void showpaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpaddActionPerformed
        if(showpadd.isSelected()){
            signupPass.setEchoChar((char)0);
        }else {
            signupPass.setEchoChar('*');
        }
    }//GEN-LAST:event_showpaddActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        changecolor(karyawan, new Color(107, 108, 113));
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        changecolor(karyawan, new Color(107, 108, 113));
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel20MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseEntered
        changecolor(supplier, new Color(107, 108, 113));
    }//GEN-LAST:event_jLabel20MouseEntered

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        changecolor(supplier, new Color(107, 108, 113));
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        changecolor(supplier, new Color(107, 108, 113));
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseExited
        changecolor(supplier, new Color(27, 35, 42));
    }//GEN-LAST:event_jLabel20MouseExited

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        changecolor(supplier, new Color(27, 35, 42));
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        changecolor(supplier, new Color(27, 35, 42));
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        changecolor(karyawan, new Color(27, 35, 42));
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        changecolor(karyawan, new Color(27, 35, 42));
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        taskbar.setVisible(true);
        PanelSignup.setVisible(true);
        PanelLogin.setVisible(false);
        panelPilihan.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void txtLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseEntered
        changecolor(plogin, new Color(67, 119, 169));
    }//GEN-LAST:event_txtLoginMouseEntered

    private void txtsignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsignupMouseEntered
        changecolor(pSignup, new Color(67, 119, 169));
    }//GEN-LAST:event_txtsignupMouseEntered

    private void txtsignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsignupMouseClicked
        taskbar.setVisible(false);
        PanelSignup.setVisible(false);
        PanelLogin.setVisible(false);
        panelPilihan.setVisible(true);
    }//GEN-LAST:event_txtsignupMouseClicked

    private void txtsignupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsignupMouseExited
        
        changecolor(pSignup, new Color(27, 35, 42));
    }//GEN-LAST:event_txtsignupMouseExited

    private void txtLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseExited
        changecolor(plogin, new Color(27, 35, 42));
    }//GEN-LAST:event_txtLoginMouseExited

    private void txtLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginMouseClicked
        taskbar.setVisible(true);
        PanelLogin.setVisible(true);
        PanelSignup.setVisible(false);
        panelPilihan.setVisible(false);
    }//GEN-LAST:event_txtLoginMouseClicked

    private void txtbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuttonMouseClicked
       new PasswordRecovery().setVisible(true); ;
        this.dispose();
    }//GEN-LAST:event_txtbuttonMouseClicked

    private void txtbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuttonMouseEntered
        changeCtext(txtbutton, new Color(67, 119, 169));
    }//GEN-LAST:event_txtbuttonMouseEntered

    private void txtbuttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuttonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuttonMousePressed

    private void txtbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbuttonMouseExited
        changeCtext(txtbutton, new Color(0, 0, 0));
    }//GEN-LAST:event_txtbuttonMouseExited

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        ca.getNama(id.getText(), txtnama);
    }//GEN-LAST:event_idActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        if("".equals(id.getText())){
            latarid.setEnabled(false);
            latarid.setVisible(true);
        }else{
            latarid.setEnabled(false);
            latarid.setVisible(false);
        }
    }//GEN-LAST:event_idKeyTyped

    private void lataridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lataridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lataridActionPerformed

    private void latarrecoveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latarrecoveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latarrecoveryActionPerformed

    private void recoverycodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recoverycodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recoverycodeActionPerformed

    private void recoverycodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_recoverycodeKeyTyped
        if("".equals(recoverycode.getText())){
            latarrecovery.setEnabled(false);
            latarrecovery.setVisible(true);
        }else{
            latarrecovery.setEnabled(false);
            latarrecovery.setVisible(false);
        }
    }//GEN-LAST:event_recoverycodeKeyTyped

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(this.getExtendedState() != FormMasuk.HIDE_ON_CLOSE){
            this.setExtendedState(FormMasuk.HIDE_ON_CLOSE);
        }else{
            this.setExtendedState(FormMasuk.NORMAL);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        changecolor(jpmax, new Color(67, 119, 169));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        changecolor(jpmax, new Color(54, 101, 179));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ca.getNama(id.getText(), txtnama);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogIn;
    public javax.swing.JPanel PanelLogin;
    public javax.swing.JPanel PanelSignup;
    private javax.swing.JPanel iconPanel;
    public javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel jpclose;
    private javax.swing.JPanel jpmax;
    private javax.swing.JPanel jpmin;
    private javax.swing.JPanel karyawan;
    private javax.swing.JTextField latarid;
    private javax.swing.JTextField latarpass;
    private javax.swing.JTextField latarrecovery;
    private javax.swing.JTextField lataruser;
    private javax.swing.JPanel pSignup;
    public javax.swing.JPanel panelPilihan;
    public javax.swing.JPasswordField pass;
    private javax.swing.JPanel plogin;
    public javax.swing.JTextField recoverycode;
    private javax.swing.JToggleButton showpadd;
    private javax.swing.JPasswordField signupPass;
    private javax.swing.JTextField signupUser;
    private javax.swing.JPanel supplier;
    public javax.swing.JPanel taskbar;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtbutton;
    public javax.swing.JLabel txtnama;
    private javax.swing.JLabel txtsignup;
    public javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
