/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataKaryawan;

import MainMenu_Dashboard_Bantuan.MenuUtama;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author acer_
 */
public class InputKaryawan extends javax.swing.JFrame {
    
    private File selectedFileFile;
    private FileInputStream fis;
    /**
     * Creates new form InputKaryawan
     */
    public InputKaryawan() {
        initComponents();
        
        ck.showdata(jTable1);
        PanelData.setVisible(false);
        btUpdare.setEnabled(false);
    }
    
    //
    ClassKaryawan1 ck = new ClassKaryawan1();
    
    private void changecolor(JPanel panel, Color warna) {
        panel.setBackground(warna);
    }
    
        // fit foto sesuai ukuran jlabel
    
    private void textBox(JComboBox box, String kab, String pos, String lengkap){
        jTextArea1.setText(box.getSelectedItem()+ ", " +kab+ ", " +pos+ ", " +lengkap);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtphoto = new javax.swing.JTextField();
        Bcari = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        labelDiv = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtkodepos = new javax.swing.JTextField();
        boxdivisi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tgllahir = new com.toedter.calendar.JDateChooser();
        boxprovinsi = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtkota = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        latarFoto = new javax.swing.JLabel();
        tampilFoto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtktp = new javax.swing.JTextField();
        boxstatus = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        panelButton = new javax.swing.JPanel();
        btUpdare = new javax.swing.JButton();
        pb1 = new javax.swing.JPanel();
        pb2 = new javax.swing.JPanel();
        btSave = new javax.swing.JButton();
        txtrtrw = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PanelData = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        latarFoto1 = new javax.swing.JLabel();
        Datatampilfoto = new javax.swing.JLabel();
        iddata = new javax.swing.JLabel();
        namadata = new javax.swing.JLabel();
        divisidata = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        toolbar = new javax.swing.JPanel();
        panelIcon = new javax.swing.JPanel();
        jPclose = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPMax = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPMin = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtphoto.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jPanel3.add(txtphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 70, -1));

        Bcari.setText("jButton1");
        Bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcariActionPerformed(evt);
            }
        });
        jPanel3.add(Bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 159, 30, -1));

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtid.setText("Id");
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel3.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 100, 30));

        labelDiv.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        labelDiv.setText("   A");
        labelDiv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(labelDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Divisi");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 90, 30));

        txtnama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtnama.setText("Nama");
        txtnama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnamaFocusLost(evt);
            }
        });
        jPanel3.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 130, 30));

        txtkodepos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtkodepos.setText("Kode pos");
        txtkodepos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtkodeposFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkodeposFocusLost(evt);
            }
        });
        jPanel3.add(txtkodepos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 130, 30));

        boxdivisi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        boxdivisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Divisi", "Admin", "Karyawan" }));
        boxdivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxdivisiActionPerformed(evt);
            }
        });
        jPanel3.add(boxdivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Tanggal Lahir");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Gender");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 100, 20));

        tgllahir.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 110, 30));

        boxprovinsi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        boxprovinsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Provinsi", "Aceh", "DKI Jakarta", "Jawa Barat", "Jawa Tengah", "Jawa Timur", "Yogyakarta" }));
        jPanel3.add(boxprovinsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 130, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton1.setText("Laki-Laki");
        jRadioButton1.setOpaque(false);
        jPanel3.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 90, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jRadioButton2.setText("Perempuan");
        jRadioButton2.setOpaque(false);
        jPanel3.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, -1));

        txtkota.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtkota.setText("Kabupaten / Kota");
        txtkota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtkotaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkotaFocusLost(evt);
            }
        });
        jPanel3.add(txtkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, 30));

        txtTelp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTelp.setText("no Telpon");
        txtTelp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelpFocusLost(evt);
            }
        });
        jPanel3.add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 130, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText(" Alamat :");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 331, 60, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 80, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("No. Telpon");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 80, 30));

        latarFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        latarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bingkaifoto2.png"))); // NOI18N
        jPanel3.add(latarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 120));

        tampilFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampilFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/foto.png"))); // NOI18N
        jPanel3.add(tampilFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 120, 120));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("no. KTP");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 80, 20));

        txtktp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtktp.setText("id KTP");
        txtktp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtktpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtktpFocusLost(evt);
            }
        });
        jPanel3.add(txtktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 130, 30));

        boxstatus.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        boxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status--", "Menikah", "Belum Menikah" }));
        jPanel3.add(boxstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 130, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setText("Nama");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Table >");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 70, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 210, 90));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/next.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setOpaque(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 350, 50, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Alamat");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, 30));

        panelButton.setBackground(new java.awt.Color(152, 201, 216));
        panelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btUpdare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/updateicon.png"))); // NOI18N
        btUpdare.setBorderPainted(false);
        btUpdare.setContentAreaFilled(false);
        btUpdare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btUpdareMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btUpdareMouseExited(evt);
            }
        });
        btUpdare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpdareActionPerformed(evt);
            }
        });
        panelButton.add(btUpdare, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 100, 70));

        pb1.setBackground(new java.awt.Color(152, 201, 216));

        javax.swing.GroupLayout pb1Layout = new javax.swing.GroupLayout(pb1);
        pb1.setLayout(pb1Layout);
        pb1Layout.setHorizontalGroup(
            pb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pb1Layout.setVerticalGroup(
            pb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelButton.add(pb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 10));

        pb2.setBackground(new java.awt.Color(152, 201, 216));

        javax.swing.GroupLayout pb2Layout = new javax.swing.GroupLayout(pb2);
        pb2.setLayout(pb2Layout);
        pb2Layout.setHorizontalGroup(
            pb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pb2Layout.setVerticalGroup(
            pb2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelButton.add(pb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, -1, 10));

        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/save.png"))); // NOI18N
        btSave.setBorderPainted(false);
        btSave.setContentAreaFilled(false);
        btSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSaveMouseExited(evt);
            }
        });
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        panelButton.add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 65));

        jPanel3.add(panelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 100, 152));

        txtrtrw.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtrtrw.setText("Alamat lengkap (Rt/ Rw)");
        txtrtrw.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtrtrwFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtrtrwFocusLost(evt);
            }
        });
        txtrtrw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrtrwActionPerformed(evt);
            }
        });
        jPanel3.add(txtrtrw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 270, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setText("id Karyawan");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 90, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton2.setText("Clear here..");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 312, 100, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 85, 600, 470));

        PanelData.setBackground(new java.awt.Color(255, 255, 255));
        PanelData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        PanelData.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 480, 190));

        jButton1.setText("delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelData.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, 40));

        jButton4.setText("Ref");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelData.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("<< Back");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        PanelData.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 30));

        latarFoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        latarFoto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bingkaifoto2.png"))); // NOI18N
        PanelData.add(latarFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 120));

        Datatampilfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Datatampilfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/foto.png"))); // NOI18N
        PanelData.add(Datatampilfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 120, 120));

        iddata.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        iddata.setText("id Karyawan");
        PanelData.add(iddata, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, 30));

        namadata.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        namadata.setText("Nama");
        PanelData.add(namadata, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 90, 30));

        divisidata.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        divisidata.setText("Divisi");
        PanelData.add(divisidata, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 90, 30));

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        PanelData.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 120, 40));

        jPanel1.add(PanelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 85, 600, 470));

        left.setPreferredSize(new java.awt.Dimension(225, 488));
        left.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/Latardatakaryawan.jpg"))); // NOI18N
        left.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 890, 550));

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setPreferredSize(new java.awt.Dimension(890, 32));
        toolbar.setLayout(new java.awt.BorderLayout());

        panelIcon.setBackground(new java.awt.Color(255, 255, 255));
        panelIcon.setPreferredSize(new java.awt.Dimension(138, 32));
        panelIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPclose.setBackground(new java.awt.Color(152, 201, 216));
        jPclose.setPreferredSize(new java.awt.Dimension(50, 50));
        jPclose.setLayout(new java.awt.BorderLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/closeToolbar.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPclose.add(jLabel11, java.awt.BorderLayout.CENTER);

        panelIcon.add(jPclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 0, -1, 25));

        jPMax.setBackground(new java.awt.Color(255, 255, 255));
        jPMax.setPreferredSize(new java.awt.Dimension(50, 50));
        jPMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPMaxMouseEntered(evt);
            }
        });
        jPMax.setLayout(new java.awt.BorderLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/maxToolBar2.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPMax.add(jLabel12, java.awt.BorderLayout.CENTER);

        panelIcon.add(jPMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 0, 50, 25));

        jPMin.setBackground(new java.awt.Color(255, 255, 255));
        jPMin.setPreferredSize(new java.awt.Dimension(50, 50));
        jPMin.setLayout(new java.awt.BorderLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/minToolBar.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPMin.add(jLabel13, java.awt.BorderLayout.CENTER);

        panelIcon.add(jPMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 32, 25));

        toolbar.add(panelIcon, java.awt.BorderLayout.LINE_END);

        jPanel1.add(toolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.dispose();
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        changecolor(jPclose, new Color(234, 44, 12));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        changecolor(jPclose, new Color(152,201,216));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if(this.getExtendedState() != InputKaryawan.MAXIMIZED_BOTH){
            this.setExtendedState(InputKaryawan.MAXIMIZED_BOTH);
        }else {
            this.setExtendedState(InputKaryawan.NORMAL);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        changecolor(jPMax, new Color(0, 149, 246));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        changecolor(jPMax, new Color(255,255,255));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jPMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPMaxMouseEntered

    }//GEN-LAST:event_jPMaxMouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if(this.getExtendedState() != InputKaryawan.HIDE_ON_CLOSE){
            this.setExtendedState(InputKaryawan.HIDE_ON_CLOSE);
        }else {
            this.setExtendedState(InputKaryawan.HIDE_ON_CLOSE);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        changecolor(jPMin, new Color(0, 149, 246));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        changecolor(jPMin, new Color(255,255,255));
    }//GEN-LAST:event_jLabel13MouseExited

    private void BcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcariActionPerformed
        ck.ambilpic(tampilFoto, txtphoto);
    }//GEN-LAST:event_BcariActionPerformed

    private void txtkotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkotaFocusGained
    if(txtkota.getText().equals("Kabupaten / Kota")){
            txtkota.setText("") ;
        }
    }//GEN-LAST:event_txtkotaFocusGained

    private void txtkotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkotaFocusLost
      if(txtkota.getText().equals("")){
            txtkota.setText("Kabupaten / Kota") ;
        }
    }//GEN-LAST:event_txtkotaFocusLost

    private void txtkodeposFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkodeposFocusGained
         if(txtkodepos.getText().equals("Kode pos")){
            txtkodepos.setText("") ;
        }
    }//GEN-LAST:event_txtkodeposFocusGained

    private void txtkodeposFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkodeposFocusLost
        if(txtkodepos.getText().equals("")){
            txtkodepos.setText("Kode pos");
        }
    }//GEN-LAST:event_txtkodeposFocusLost

    private void boxdivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxdivisiActionPerformed
        if(boxdivisi.getSelectedItem() == "Admin"){
            labelDiv.setText("A");
        }else if(boxdivisi.getSelectedItem() == "Karyawan"){
            labelDiv.setText("K");
        }else {
            labelDiv.setText("   A");
        }
    }//GEN-LAST:event_boxdivisiActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jPanel3.setVisible(false);
        PanelData.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ck.deleteKaryawan(jTable1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ck.showdata(jTable1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jPanel3.setVisible(true);
        PanelData.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        textBox(boxprovinsi, txtkota.getText(), txtkodepos.getText(), txtrtrw.getText());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusGained
        if(txtid.getText().equals("Id")){
            txtid.setText("") ;
            }
    }//GEN-LAST:event_txtidFocusGained

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        if(txtid.getText().equals("")){
            txtid.setText("Id") ;
            }
    }//GEN-LAST:event_txtidFocusLost

    private void txtktpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtktpFocusGained
        if(txtktp.getText().equals("id KTP")){
            txtktp.setText("") ;
            }
    }//GEN-LAST:event_txtktpFocusGained

    private void txtktpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtktpFocusLost
        if(txtktp.getText().equals("")){
            txtktp.setText("id KTP") ;
            }
    }//GEN-LAST:event_txtktpFocusLost

    private void txtTelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelpFocusGained
        if(txtTelp.getText().equals("no Telpon")){
            txtTelp.setText("") ;
            }
    }//GEN-LAST:event_txtTelpFocusGained

    private void txtTelpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelpFocusLost
        if(txtTelp.getText().equals("")){
            txtTelp.setText("no Telpon") ;
            }
    }//GEN-LAST:event_txtTelpFocusLost

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setBackground(new Color(0, 190, 164));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton5MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(new Color(0, 190, 164));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jLabel4MouseExited

    private void txtnamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusGained
        if(txtnama.getText().equals("Nama")){
            txtnama.setText("") ;
            }
    }//GEN-LAST:event_txtnamaFocusGained

    private void txtnamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnamaFocusLost
        if(txtnama.getText().equals("")){
            txtnama.setText("Nama") ;
            }
    }//GEN-LAST:event_txtnamaFocusLost

    private void txtrtrwFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrtrwFocusGained
        if(txtrtrw.getText().equals("Alamat lengkap (Rt/ Rw)")){
            txtrtrw.setText("");
        }
    }//GEN-LAST:event_txtrtrwFocusGained

    private void txtrtrwFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtrtrwFocusLost
        if(txtrtrw.getText().equals("")){
            txtrtrw.setText("Alamat lengkap (Rt/ Rw)");
        }
    }//GEN-LAST:event_txtrtrwFocusLost

    private void txtrtrwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrtrwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrtrwActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       ck.TabletoTextField(jTable1, iddata, namadata, divisidata, Datatampilfoto);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ck.EditData(btUpdare, txtid, btSave, jTable1, jPanel3, PanelData, boxstatus, boxdivisi, txtid, txtnama, txtTelp, txtktp, tgllahir, 
                jRadioButton1, jRadioButton2, jTextArea1);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
       jLabel2.setForeground(new Color(0, 190, 164));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ck.settxt(boxstatus, boxdivisi, txtid, txtnama, txtTelp, txtktp, jTextArea1, boxprovinsi, txtkota, txtkodepos, txtrtrw);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        String rd ;
       if(jRadioButton1.isSelected()){
           rd = jRadioButton1.getActionCommand();
       }else {
           rd = jRadioButton2.getActionCommand();
       }
       
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String tgl = String.valueOf(sdf.format(tgllahir.getDate()));
               
        ck.saveKaryawan(labelDiv, txtid.getText(), txtnama.getText(), boxdivisi.getSelectedItem().toString(), rd, boxstatus.getSelectedItem().toString(), 
                txtktp.getText(), jTextArea1.getText(), txtTelp.getText(), tgl);
    }//GEN-LAST:event_btSaveActionPerformed

    private void btUpdareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpdareActionPerformed
        String rd ;
       if(jRadioButton1.isSelected()){
           rd = jRadioButton1.getActionCommand();
       }else {
           rd = jRadioButton2.getActionCommand();
       }
       
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String tgl = String.valueOf(sdf.format(tgllahir.getDate()));
        
        ck.updateKaryawan(btUpdare, txtid, btSave, jTextArea1, txtid.getText(), txtnama.getText(), boxdivisi.getSelectedItem().toString(), rd, boxstatus.getSelectedItem().toString(), 
                txtktp.getText(), jTextArea1.getText(), txtTelp.getText(), tgl,
                boxstatus, boxdivisi, txtnama, txtTelp, txtktp,
                boxdivisi, txtkota, txtkodepos, txtrtrw);
    }//GEN-LAST:event_btUpdareActionPerformed

    private void btSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseEntered
        changecolor(pb1, new Color(0, 190, 164));
    }//GEN-LAST:event_btSaveMouseEntered

    private void btSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseClicked
        
    }//GEN-LAST:event_btSaveMouseClicked

    private void btUpdareMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUpdareMouseEntered
        changecolor(pb2, new Color(0, 190, 164));
    }//GEN-LAST:event_btUpdareMouseEntered

    private void btUpdareMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUpdareMouseExited
        changecolor(pb2, new Color(152,201,216));
    }//GEN-LAST:event_btUpdareMouseExited

    private void btSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSaveMouseExited
        changecolor(pb1, new Color(152,201,216));
    }//GEN-LAST:event_btSaveMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcari;
    private javax.swing.JLabel Datatampilfoto;
    private javax.swing.JPanel PanelData;
    private javax.swing.JComboBox<String> boxdivisi;
    private javax.swing.JComboBox<String> boxprovinsi;
    private javax.swing.JComboBox<String> boxstatus;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btUpdare;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel divisidata;
    private javax.swing.JLabel iddata;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPMax;
    private javax.swing.JPanel jPMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPclose;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelDiv;
    private javax.swing.JLabel latarFoto;
    private javax.swing.JLabel latarFoto1;
    private javax.swing.JPanel left;
    private javax.swing.JLabel namadata;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelIcon;
    private javax.swing.JPanel pb1;
    private javax.swing.JPanel pb2;
    private javax.swing.JLabel tampilFoto;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JPanel toolbar;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtkodepos;
    private javax.swing.JTextField txtkota;
    private javax.swing.JTextField txtktp;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtphoto;
    private javax.swing.JTextField txtrtrw;
    // End of variables declaration//GEN-END:variables
}
