/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataProduk_dan_Supplier;

import DataGudang.StokData;
import MainMenu_Dashboard_Bantuan.MenuUtama;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author acer_
 */
public class InputDataProduk extends javax.swing.JFrame {

    /**
     * Creates new form InputDataProduk
     */
    public InputDataProduk() {
        initComponents();
        
        cp.addcBox(pboxsupp);
        pbuttonupdate.setEnabled(false);
    }
    
    
    //
    ClassProduk1 cp = new ClassProduk1();
    
    private void changecolor(JPanel panel, Color color){
        panel.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        panelIcon = new javax.swing.JPanel();
        jPclose = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPMax = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPMin = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        plabelfoto = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ptxtkode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ptxtnama = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ptxtharga = new javax.swing.JTextField();
        pbuttoSAve = new javax.swing.JButton();
        pbuttonupdate = new javax.swing.JButton();
        pboxtipe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pboxsupp = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        panelIcon.setBackground(new java.awt.Color(255, 255, 255));
        panelIcon.setPreferredSize(new java.awt.Dimension(138, 32));
        panelIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPclose.setBackground(new java.awt.Color(152, 201, 216));
        jPclose.setPreferredSize(new java.awt.Dimension(50, 50));
        jPclose.setLayout(new java.awt.BorderLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/closeToolbar.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPclose.add(jLabel11, java.awt.BorderLayout.CENTER);

        panelIcon.add(jPclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 0, -1, 25));

        jPMax.setBackground(new java.awt.Color(255, 255, 255));
        jPMax.setPreferredSize(new java.awt.Dimension(50, 50));
        jPMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPMaxMouseEntered(evt);
            }
        });
        jPMax.setLayout(new java.awt.BorderLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/maxToolBar2.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        jPMax.add(jLabel12, java.awt.BorderLayout.CENTER);

        panelIcon.add(jPMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 0, 50, 25));

        jPMin.setBackground(new java.awt.Color(255, 255, 255));
        jPMin.setPreferredSize(new java.awt.Dimension(50, 50));
        jPMin.setLayout(new java.awt.BorderLayout());

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/minToolBar.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        jPMin.add(jLabel13, java.awt.BorderLayout.CENTER);

        panelIcon.add(jPMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 32, 25));

        jPanel5.add(panelIcon, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/dataprodukLatar.jpg"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(820, 120));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 230));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(820, 220));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plabelfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plabelfoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(plabelfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, 140));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, -1));

        cari.setText("...");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel2.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 24, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Kode Article");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 90, 30));

        ptxtkode.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(ptxtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 119, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Nama Produk");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 100, 30));

        ptxtnama.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.add(ptxtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 120, 30));

        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 400, 220));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Harga");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Jenis Produk");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 100, 30));

        ptxtharga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel3.add(ptxtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 120, 30));

        pbuttoSAve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/save.png"))); // NOI18N
        pbuttoSAve.setBorderPainted(false);
        pbuttoSAve.setContentAreaFilled(false);
        pbuttoSAve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbuttoSAveActionPerformed(evt);
            }
        });
        jPanel3.add(pbuttoSAve, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 90, 70));

        pbuttonupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/updateicon.png"))); // NOI18N
        pbuttonupdate.setBorderPainted(false);
        pbuttonupdate.setContentAreaFilled(false);
        pbuttonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbuttonupdateActionPerformed(evt);
            }
        });
        jPanel3.add(pbuttonupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 90, 60));

        pboxtipe.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pboxtipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipe Produk", "Pakaian", "Sepatu", "Tas" }));
        jPanel3.add(pboxtipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 120, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("To table -->");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Id Supplier");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 90, 23));

        pboxsupp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pboxsupp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier" }));
        jPanel3.add(pboxsupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 119, 30));

        jPanel6.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 410, 220));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 840, 250));

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(840, 515));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.dispose();
        new MenuUtama().setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        changecolor(jPclose, new Color(234, 44, 12));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        changecolor(jPclose, new Color(152,201,216));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if(this.getExtendedState() != InputDataProduk.MAXIMIZED_BOTH){
            this.setExtendedState(InputDataProduk.MAXIMIZED_BOTH);
        }else {
            this.setExtendedState(InputDataProduk.NORMAL);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        changecolor(jPMax, new Color(0, 149, 246));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        changecolor(jPMax, new Color(255,255,255));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jPMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPMaxMouseEntered

    }//GEN-LAST:event_jPMaxMouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        if(this.getExtendedState() != InputDataProduk.HIDE_ON_CLOSE){
            this.setExtendedState(InputDataProduk.HIDE_ON_CLOSE);
        }else {
            this.setExtendedState(InputDataProduk.HIDE_ON_CLOSE);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        changecolor(jPMin, new Color(0, 149, 246));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        changecolor(jPMin, new Color(255,255,255));
    }//GEN-LAST:event_jLabel13MouseExited

    private void pbuttoSAveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbuttoSAveActionPerformed
        cp.saveProduk(pboxsupp.getSelectedItem().toString(), ptxtkode.getText(), ptxtnama.getText(), 
                      pboxtipe.getSelectedItem().toString(), ptxtharga.getText());
    }//GEN-LAST:event_pbuttoSAveActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        cp.ambilpic(plabelfoto, jTextField1);
    }//GEN-LAST:event_cariActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new StokData().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void pbuttonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbuttonupdateActionPerformed
        String idSup = pboxsupp.getSelectedItem().toString();
        String namaProduk = ptxtnama.getText();
        String jenis = pboxtipe.getSelectedItem().toString();
        String harga = ptxtharga.getText();
        
        cp.updateProduk(idSup, ptxtkode, namaProduk, jenis, harga, pbuttoSAve, pbuttonupdate);
    }//GEN-LAST:event_pbuttonupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputDataProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPMax;
    private javax.swing.JPanel jPMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPclose;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel panelIcon;
    public javax.swing.JComboBox<String> pboxsupp;
    public javax.swing.JComboBox<String> pboxtipe;
    public javax.swing.JButton pbuttoSAve;
    public javax.swing.JButton pbuttonupdate;
    public javax.swing.JLabel plabelfoto;
    public javax.swing.JTextField ptxtharga;
    public javax.swing.JTextField ptxtkode;
    public javax.swing.JTextField ptxtnama;
    // End of variables declaration//GEN-END:variables
}
