/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataProduk_dan_Supplier;

import MainMenu_Dashboard_Bantuan.MenuUtama;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author acer_
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Supplier() {
        initComponents();
        
        behind.setVisible(false);
        cs.loadSupplier(jTable1);
        jButton5.setEnabled(false);
        linekiri.setVisible(false);
        linekanan.setVisible(false);
    }

    //
    ClassSupplier1 cs = new ClassSupplier1();
    
    
    private void changecolor(JPanel panel, Color warna){
        panel.setBackground(warna);
    }
    
    private void menuBar(JPanel pputih, JPanel pbiru, JPanel pclose, JPanel ptrue, JLabel label, JPanel linetrue, JPanel linefalse){
        pputih.setBackground(new Color(255,255,255));
        pbiru.setBackground(new Color(54,101,179));
        label.setForeground(new Color(0,0,0));
        linetrue.setBackground(new Color(152,201,216));
        
        linetrue.setVisible(true);
        linefalse.setVisible(false);
        
        pclose.setVisible(false);
        ptrue.setVisible(true);
    }
    private void changeCText(JLabel label, Color wr ){
        label.setForeground(wr);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        toolbar = new javax.swing.JPanel();
        iconPanel = new javax.swing.JPanel();
        jpclose = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpmax = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpmin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        front = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidSupp = new javax.swing.JTextField();
        txtnamaSupp = new javax.swing.JTextField();
        txtalamatKantor = new javax.swing.JTextField();
        txttelpKantor = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        behind = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        menubar = new javax.swing.JPanel();
        line1 = new javax.swing.JPanel();
        line2 = new javax.swing.JPanel();
        menu1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        linekiri = new javax.swing.JPanel();
        menu2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        linekanan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/latarMember.jpg"))); // NOI18N
        jPanel2.add(jLabel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 410));

        toolbar.setBackground(new java.awt.Color(255, 255, 255));
        toolbar.setPreferredSize(new java.awt.Dimension(720, 32));
        toolbar.setLayout(new java.awt.BorderLayout());

        iconPanel.setBackground(new java.awt.Color(255, 255, 255));
        iconPanel.setPreferredSize(new java.awt.Dimension(138, 25));
        iconPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpclose.setBackground(new java.awt.Color(152, 201, 216));
        jpclose.setPreferredSize(new java.awt.Dimension(35, 35));
        jpclose.setLayout(new java.awt.BorderLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/closeToolbar.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jpclose.add(jLabel10, java.awt.BorderLayout.CENTER);

        iconPanel.add(jpclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 50, 25));

        jpmax.setBackground(new java.awt.Color(255, 255, 255));
        jpmax.setPreferredSize(new java.awt.Dimension(35, 35));
        jpmax.setLayout(new java.awt.BorderLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/maxToolBar2.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jpmax.add(jLabel9, java.awt.BorderLayout.CENTER);

        iconPanel.add(jpmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 25));

        jpmin.setBackground(new java.awt.Color(255, 255, 255));
        jpmin.setPreferredSize(new java.awt.Dimension(35, 35));
        jpmin.setLayout(new java.awt.BorderLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/minToolBar.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jpmin.add(jLabel8, java.awt.BorderLayout.CENTER);

        iconPanel.add(jpmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 25));

        toolbar.add(iconPanel, java.awt.BorderLayout.LINE_END);

        jPanel1.add(toolbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 580, 32));

        front.setBackground(new java.awt.Color(255, 255, 255));
        front.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Id Supplier");
        front.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Nama Supplier");
        front.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Alamat");
        front.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Telpon Kantor");
        front.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 100, 30));

        txtidSupp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        front.add(txtidSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 150, 30));

        txtnamaSupp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        front.add(txtnamaSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 150, 30));

        txtalamatKantor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtalamatKantor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatKantorActionPerformed(evt);
            }
        });
        front.add(txtalamatKantor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 150, 30));

        txttelpKantor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        front.add(txttelpKantor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 150, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/save.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        front.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 80, 70));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/updateicon.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        front.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, 70));

        jPanel1.add(front, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 83, 580, 327));

        behind.setBackground(new java.awt.Color(255, 255, 255));
        behind.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        behind.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 130, 30));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        behind.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 480, 140));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/tabelicon.png"))); // NOI18N
        jButton1.setText("Edit");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        behind.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/deleteicon.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        behind.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 70, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/refresh.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        behind.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, 40));

        jPanel1.add(behind, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 83, 580, 327));

        menubar.setBackground(new java.awt.Color(54, 101, 179));
        menubar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        line1.setBackground(new java.awt.Color(54, 101, 179));

        javax.swing.GroupLayout line1Layout = new javax.swing.GroupLayout(line1);
        line1.setLayout(line1Layout);
        line1Layout.setHorizontalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        line1Layout.setVerticalGroup(
            line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        menubar.add(line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 7));

        line2.setBackground(new java.awt.Color(54, 101, 179));

        javax.swing.GroupLayout line2Layout = new javax.swing.GroupLayout(line2);
        line2.setLayout(line2Layout);
        line2Layout.setHorizontalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        line2Layout.setVerticalGroup(
            line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        menubar.add(line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        menu1.setBackground(new java.awt.Color(54, 101, 179));
        menu1.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/addIcon.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        menu1.add(jLabel5, java.awt.BorderLayout.CENTER);

        linekiri.setBackground(new java.awt.Color(54, 101, 179));
        linekiri.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout linekiriLayout = new javax.swing.GroupLayout(linekiri);
        linekiri.setLayout(linekiriLayout);
        linekiriLayout.setHorizontalGroup(
            linekiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        linekiriLayout.setVerticalGroup(
            linekiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        menu1.add(linekiri, java.awt.BorderLayout.LINE_START);

        menubar.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 100, 43));

        menu2.setBackground(new java.awt.Color(54, 101, 179));
        menu2.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/tabelicon.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        menu2.add(jLabel6, java.awt.BorderLayout.CENTER);

        linekanan.setBackground(new java.awt.Color(54, 101, 179));
        linekanan.setPreferredSize(new java.awt.Dimension(5, 43));

        javax.swing.GroupLayout linekananLayout = new javax.swing.GroupLayout(linekanan);
        linekanan.setLayout(linekananLayout);
        linekananLayout.setHorizontalGroup(
            linekananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        linekananLayout.setVerticalGroup(
            linekananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        menu2.add(linekanan, java.awt.BorderLayout.LINE_START);

        menubar.add(menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 7, 100, 43));

        jPanel1.add(menubar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 33, 580, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
        new MenuUtama().setVisible(true);
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        changecolor(jpclose, new Color(234, 44, 12));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        changecolor(jpclose, new Color(152,201,216));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        changecolor(jpmax, new Color(54, 101, 179));
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        changecolor(jpmax, new Color(255,255,255));
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(this.getExtendedState() != Supplier.HIDE_ON_CLOSE){
            this.setExtendedState(Supplier.HIDE_ON_CLOSE);
        }else{
            this.setExtendedState(Supplier.NORMAL);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        changecolor(jpmin, new Color(54, 101, 179));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        changecolor(jpmin, new Color (255,255,255));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        menuBar(menu1, menu2, behind, front, jLabel5, linekiri, linekanan);
        jLabel6.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        menuBar(menu2, menu1, front, behind, jLabel6, linekanan, linekiri);
        jLabel5.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        line1.setBackground(new Color(152,201,216));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        line1.setBackground(new Color(54,101,179));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        line2.setBackground(new Color(54,101,179));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        line2.setBackground(new Color(152,201,216));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void txtalamatKantorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatKantorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatKantorActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cs.saveSupplier(txtidSupp.getText(), txtnamaSupp.getText(), txtalamatKantor.getText(), txttelpKantor.getText(),
                        txtidSupp, txtnamaSupp, txtalamatKantor, txttelpKantor);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cs.loadSupplier(jTable1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       cs.deleteData(jTable1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cs.getTabletoTextField(jTable1, jLabel6, jLabel5, menu1, menu2, behind, front, txtidSupp, 
                                txtnamaSupp, txtalamatKantor, txttelpKantor, jButton4, jButton5);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        cs.updateSupplier(txtidSupp.getText(), txtnamaSupp.getText(), txtalamatKantor.getText(), txttelpKantor.getText(), jButton4, txtidSupp
        , jButton5);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel behind;
    private javax.swing.JPanel front;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel jpclose;
    private javax.swing.JPanel jpmax;
    private javax.swing.JPanel jpmin;
    private javax.swing.JPanel line1;
    private javax.swing.JPanel line2;
    private javax.swing.JPanel linekanan;
    private javax.swing.JPanel linekiri;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menubar;
    private javax.swing.JPanel toolbar;
    private javax.swing.JTextField txtalamatKantor;
    private javax.swing.JTextField txtidSupp;
    private javax.swing.JTextField txtnamaSupp;
    private javax.swing.JTextField txttelpKantor;
    // End of variables declaration//GEN-END:variables
}
