/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DataGudang;

import DataGudang.ClassGudang1;
import DataProduk_dan_Supplier.ClassProduk1;
import DataProduk_dan_Supplier.InputDataProduk;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author acer_
 */
public class StokData extends javax.swing.JFrame {
DefaultTableModel dtm;
    /**
     * Creates new form StokData
     */
    public StokData() {
        initComponents();
        
        cg.showdataIDProduk(jTable1, jLabel8);
        cg.cBoxSupp(jComboBox1);
        
    }
    
    private void filter(String list){
        TableRowSorter <DefaultTableModel> trs = new TableRowSorter <> (dtm);
        jTable1.setRowSorter(trs);
        
        if(!list.equals("Brand")){
            trs.setRowFilter(RowFilter.regexFilter(list));
        }else {
            jTable1.setRowSorter(trs);
        }
    }
    private void sorter(){
        String a = jComboBox1.getSelectedItem().toString();
        filter (a);
    } 
    
    //
    ClassGudang1 cg = new ClassGudang1();
    
    public void changecolor (JPanel panel, Color rand){
        panel.setBackground(rand);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Taskbar = new javax.swing.JPanel();
        panelIcon = new javax.swing.JPanel();
        jPclose = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPMax = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPMin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rightpanel = new javax.swing.JPanel();
        panelIdStok = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LabelProduk = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtcari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBsearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Taskbar.setBackground(new java.awt.Color(255, 255, 255));
        Taskbar.setPreferredSize(new java.awt.Dimension(820, 32));
        Taskbar.setLayout(new java.awt.BorderLayout());

        panelIcon.setBackground(new java.awt.Color(255, 255, 255));
        panelIcon.setPreferredSize(new java.awt.Dimension(140, 50));
        panelIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPclose.setBackground(new java.awt.Color(152, 201, 216));
        jPclose.setPreferredSize(new java.awt.Dimension(50, 50));
        jPclose.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/closeToolbar.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPclose.add(jLabel1, java.awt.BorderLayout.CENTER);

        panelIcon.add(jPclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 0, -1, 25));

        jPMax.setBackground(new java.awt.Color(255, 255, 255));
        jPMax.setPreferredSize(new java.awt.Dimension(50, 50));
        jPMax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPMaxMouseEntered(evt);
            }
        });
        jPMax.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/maxToolBar2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPMax.add(jLabel3, java.awt.BorderLayout.CENTER);

        panelIcon.add(jPMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 0, 50, 25));

        jPMin.setBackground(new java.awt.Color(255, 255, 255));
        jPMin.setPreferredSize(new java.awt.Dimension(50, 50));
        jPMin.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/minToolBar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPMin.add(jLabel2, java.awt.BorderLayout.CENTER);

        panelIcon.add(jPMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 32, 25));

        Taskbar.add(panelIcon, java.awt.BorderLayout.LINE_END);

        jPanel1.add(Taskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        jPanel4.setPreferredSize(new java.awt.Dimension(200, 478));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/LatarTabel.jpg"))); // NOI18N
        jPanel4.add(jLabel10, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 860, 250));

        rightpanel.setBackground(new java.awt.Color(255, 255, 255));
        rightpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rightpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIdStok.setBackground(new java.awt.Color(120, 156, 172));
        panelIdStok.setPreferredSize(new java.awt.Dimension(720, 250));
        panelIdStok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelIdStok.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 22, 160, 140));

        LabelProduk.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        LabelProduk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelProduk.setText("Nama Produk");
        panelIdStok.add(LabelProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 119, 26));

        rightpanel.add(panelIdStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 220));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        rightpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 600, 200));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/deleteicon.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        rightpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 120, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/tabelicon.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        rightpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 110, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/refresh.png"))); // NOI18N
        jButton3.setText("Refresh");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        rightpanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 130, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Cari Berdasarkan Nama");
        rightpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 130, 26));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Filter By");
        rightpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 119, 26));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel8.setText("Jumlah Product");
        rightpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 119, 30));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brand" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        rightpanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 156, 30));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Article" }));
        rightpanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 156, 30));

        txtcari.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        rightpanel.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 156, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Sort By");
        rightpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 119, 26));

        jBsearch.setText("jButton4");
        jBsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsearchActionPerformed(evt);
            }
        });
        rightpanel.add(jBsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 40, 30));

        jPanel1.add(rightpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 840, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        changecolor(jPclose, new Color(234, 44, 12));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        changecolor(jPclose, new Color(240,240,240));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jPMaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPMaxMouseEntered
       
    }//GEN-LAST:event_jPMaxMouseEntered

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        changecolor(jPMin, new Color(0, 149, 246));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    this.dispose();
    new InputDataProduk().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
      changecolor(jPMax, new Color(0, 149, 246));  
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        changecolor(jPMax, new Color(255,255,255));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        changecolor(jPMin, new Color(255,255,255));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(this.getExtendedState() != StokData.MAXIMIZED_BOTH){
            this.setExtendedState(StokData.MAXIMIZED_BOTH);
        }else {
            this.setExtendedState(StokData.NORMAL);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(this.getExtendedState() != StokData.HIDE_ON_CLOSE){
            this.setExtendedState(StokData.HIDE_ON_CLOSE);
        }else {
            this.setExtendedState(StokData.HIDE_ON_CLOSE);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        cg.clicktoTable(jTable1, LabelProduk, jLabel4);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jBsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsearchActionPerformed
       cg.searchData(txtcari.getText(), jTable1);
    }//GEN-LAST:event_jBsearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cg.showdataIDProduk(jTable1, jLabel8);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InputDataProduk dp = new InputDataProduk();
        cg.EditTable(dp, this, jTable1, dp.ptxtkode, dp.ptxtnama, dp.pboxsupp, dp.pboxtipe, dp.ptxtharga, dp.plabelfoto, 
                      dp.pbuttoSAve, dp.pbuttonupdate);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cg.deleteProduk(jTable1);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelProduk;
    private javax.swing.JPanel Taskbar;
    private javax.swing.JButton jBsearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPMax;
    private javax.swing.JPanel jPMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPclose;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelIcon;
    private javax.swing.JPanel panelIdStok;
    private javax.swing.JPanel rightpanel;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
