/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainMenu_Dashboard_Bantuan;

import DataGudang.InputDataStokGudang;
import DataGudang.StokData;
import DataKaryawan.InputKaryawan;
import DataMember.Member;
import DataProduk_dan_Supplier.InputDataProduk;
import DataProduk_dan_Supplier.Supplier;
import DataTransaksi.InputTransaksi;
import Form_Login_Daftar_Recovery.ClassAkun1;
import java.awt.Color;
import java.awt.Image;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author acer_
 */
public class MenuUtama extends javax.swing.JFrame {

    boolean a=true;
    Statement st;
    PreparedStatement pst;
    ResultSet rs;
    
    Connection connect = DatabaseConnect.DatabaseConnect.getKoneksi("localhost", "3306", "root", "", "database_ooptugasakhir");
    
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        
        menushowhide(Menu, a, jLabel4);
            changecolor(dashboardMenu, new Color(78,135,194));
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
        
            dashboard();
            txtDashboard.setVisible(false);
            dashboarddivisi2.setVisible(false);
    }
    
    
    private void dashboard(){
        try{
            String mysql = "SELECT * FROM data_karyawan where id_karyawan ='"+dashboardid.getText()+"' ";
            st = connect.createStatement();
            rs = st.executeQuery(mysql);
            
        while(rs.next()){    
            if(dashboardid.getText().equals(rs.getString("id_karyawan"))){
            
                dashboardnama.setText(rs.getString("nama_karyawan"));
                dashboarddivisi2.setText(rs.getString("divisi"));
            }
        }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        panelIcon = new javax.swing.JPanel();
        close = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Max = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Min = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        dashboardMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        setting = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dashboardView = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dashboardusername = new javax.swing.JLabel();
        dashboardid = new javax.swing.JLabel();
        dashboardnama = new javax.swing.JLabel();
        dashboarddivisi1 = new javax.swing.JLabel();
        txtDashboard = new javax.swing.JLabel();
        dashboarddivisi2 = new javax.swing.JLabel();
        tampilFoto = new javax.swing.JLabel();
        latarFoto = new javax.swing.JLabel();
        RightMenu = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(5, 10, 46));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(820, 32));
        header.setLayout(new java.awt.BorderLayout());

        panelIcon.setBackground(new java.awt.Color(5, 10, 46));
        panelIcon.setPreferredSize(new java.awt.Dimension(138, 32));
        panelIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setBackground(new java.awt.Color(152, 201, 216));
        close.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/closeToolbar3.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        close.add(jLabel1, java.awt.BorderLayout.CENTER);

        panelIcon.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 50, 25));

        Max.setBackground(new java.awt.Color(5, 10, 46));
        Max.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/maxToolBar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        Max.add(jLabel2, java.awt.BorderLayout.CENTER);

        panelIcon.add(Max, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 25));

        Min.setBackground(new java.awt.Color(5, 10, 46));
        Min.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/minToolBar2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        Min.add(jLabel3, java.awt.BorderLayout.CENTER);

        panelIcon.add(Min, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 25));

        header.add(panelIcon, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        Menu.setPreferredSize(new java.awt.Dimension(300, 440));
        Menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(5, 10, 46));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 460));
        MenuIcon.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(5, 10, 46));
        jPanel3.setPreferredSize(new java.awt.Dimension(50, 120));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(5, 10, 46));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 7));

        dashboardMenu.setBackground(new java.awt.Color(5, 10, 46));
        dashboardMenu.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/dashboard.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        dashboardMenu.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel3.add(dashboardMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 7, 50, 50));

        jPanel8.setBackground(new java.awt.Color(5, 10, 46));
        jPanel8.setPreferredSize(new java.awt.Dimension(50, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 57, 50, 7));

        setting.setBackground(new java.awt.Color(5, 10, 46));
        setting.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/setting2.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        setting.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel3.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 64, 50, 50));

        MenuIcon.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        Menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        dashboardView.setBackground(new java.awt.Color(25, 29, 74));
        dashboardView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DASHBOARD");
        dashboardView.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 33, -1, -1));

        dashboardusername.setBackground(new java.awt.Color(255, 255, 255));
        dashboardusername.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        dashboardusername.setForeground(new java.awt.Color(255, 255, 255));
        dashboardusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardusername.setText("@username");
        dashboardView.add(dashboardusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 66, -1));

        dashboardid.setBackground(new java.awt.Color(255, 255, 255));
        dashboardid.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        dashboardid.setForeground(new java.awt.Color(255, 255, 255));
        dashboardid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardid.setText("id Karyawan");
        dashboardView.add(dashboardid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        dashboardnama.setBackground(new java.awt.Color(255, 255, 255));
        dashboardnama.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        dashboardnama.setForeground(new java.awt.Color(255, 255, 255));
        dashboardnama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboardnama.setText("Nama");
        dashboardView.add(dashboardnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        dashboarddivisi1.setBackground(new java.awt.Color(255, 255, 255));
        dashboarddivisi1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        dashboarddivisi1.setForeground(new java.awt.Color(255, 255, 255));
        dashboarddivisi1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboarddivisi1.setText("Divisi");
        dashboardView.add(dashboarddivisi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        txtDashboard.setBackground(new java.awt.Color(255, 255, 255));
        txtDashboard.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtDashboard.setForeground(new java.awt.Color(255, 255, 255));
        txtDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDashboard.setText("DASHBOARD2");
        dashboardView.add(txtDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 33, -1, -1));

        dashboarddivisi2.setBackground(new java.awt.Color(255, 255, 255));
        dashboarddivisi2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        dashboarddivisi2.setForeground(new java.awt.Color(255, 255, 255));
        dashboarddivisi2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboarddivisi2.setText("Divisi2");
        dashboardView.add(dashboarddivisi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        tampilFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tampilFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/foto.png"))); // NOI18N
        dashboardView.add(tampilFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 61, 118, 118));

        latarFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        latarFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bingkaifoto.png"))); // NOI18N
        dashboardView.add(latarFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 120, 120));

        Menu.add(dashboardView, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        RightMenu.setBackground(new java.awt.Color(78, 135, 194));
        RightMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/supply.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        RightMenu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 96, 96));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/admin.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        RightMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 96, 96));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/beli stok.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        RightMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 96, 96));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/bayar.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        RightMenu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 96, 96));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        RightMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 96, 96));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Supplier");
        RightMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 100, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Data Produk");
        RightMenu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 100, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Data Member");
        RightMenu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 100, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data Masuk Gudang");
        RightMenu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 120, 20));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/data.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/stok2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        RightMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 96, 96));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Data Pegawai");
        RightMenu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 100, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Transaksi");
        RightMenu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 100, 20));

        getContentPane().add(RightMenu, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(820, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void changecolor (JPanel panel, Color rand){
        panel.setBackground(rand);
    }
    
    public void munculkiri (JPanel h1, JPanel h2, int bolean){
        if (bolean == 1) {
            h1.setBackground(new Color(25, 29, 74));
            h2.setBackground(new Color(5,10,46));
        }else {
            h2.setBackground(new Color(25, 29, 74));
            h1.setBackground(new Color(5,10,46));
        }
    }
    
    public void changeimage (JLabel button, String icon ){
        ImageIcon img = new ImageIcon(getClass().getResource(icon));
        button.setIcon(img);
    }
    
    public void menushowhide (JPanel hideshow, boolean leftmenu, JLabel button){
        if (leftmenu == true){
        hideshow.setPreferredSize(new Dimension(50, hideshow.getHeight()));
        changeimage(button,"/pic/dashboard.png");
        
        }else{
            hideshow.setPreferredSize(new Dimension(300, hideshow.getHeight()));
            changeimage(button,"/pic/dashboard.png");
        }
    }
    
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
            changecolor(close, new Color(234, 44, 12));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
       changecolor(close, new Color(152,201,216));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if (this.getExtendedState() != MenuUtama.MAXIMIZED_BOTH){
            this.setExtendedState(MenuUtama.MAXIMIZED_BOTH);
        }else {
            this.setExtendedState(MenuUtama.NORMAL);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        changecolor(Max, new Color(54, 101, 179));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        changecolor(Max, new Color(5,10,46));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        changecolor(jPanel4, new Color(247, 78, 103));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        changecolor(jPanel4, new Color(5,10,46));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        munculkiri(setting, dashboardMenu, 1);
        //hideshow
        if(a== true){
            menushowhide(Menu, a, jLabel4);
            changecolor(dashboardMenu, new Color(78,135,194));
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
            
            //
        txtDashboard.setVisible(true);
        dashboarddivisi2.setVisible(true);
        
        //
        jLabel7.setVisible(false);
        dashboardMenu.setVisible(true);
        dashboardid.setVisible(false);
        dashboardusername.setVisible(false);
        dashboardnama.setVisible(false);    
        }else {
            menushowhide(Menu, a, jLabel4);            
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        changecolor(jPanel8, new Color(5, 177, 150));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        changecolor(jPanel8, new Color(5,10,46));
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        munculkiri(dashboardMenu, setting, 1);
        //hideshow
        if(a== true){
            menushowhide(Menu, a, jLabel4);
            changecolor(dashboardMenu, new Color(78,135,194));
            SwingUtilities.updateComponentTreeUI(this);
            a=false;
            
            //
        jLabel7.setVisible(true);
        dashboardMenu.setVisible(true);
        dashboardid.setVisible(true);
        dashboardusername.setVisible(true);
        dashboardnama.setVisible(true);
            //
        txtDashboard.setVisible(false);
        dashboarddivisi2.setVisible(false);    
        }else {
            menushowhide(Menu, a, jLabel4);            
            SwingUtilities.updateComponentTreeUI(this);
            a=true;
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        changecolor(Min, new Color(54, 101, 179));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        changecolor(Min, new Color(5,10,46));
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        if(this.getExtendedState() != MenuUtama.HIDE_ON_CLOSE){
            this.setExtendedState(MenuUtama.HIDE_ON_CLOSE);
        }else {
            this.setExtendedState(MenuUtama.NORMAL);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new InputDataProduk().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Member().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new InputKaryawan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new InputTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new InputDataStokGudang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Supplier().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Max;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel Min;
    private javax.swing.JPanel RightMenu;
    private javax.swing.JPanel close;
    private javax.swing.JPanel dashboardMenu;
    private javax.swing.JPanel dashboardView;
    public javax.swing.JLabel dashboarddivisi1;
    public javax.swing.JLabel dashboarddivisi2;
    public javax.swing.JLabel dashboardid;
    public javax.swing.JLabel dashboardnama;
    public javax.swing.JLabel dashboardusername;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel latarFoto;
    private javax.swing.JPanel panelIcon;
    private javax.swing.JPanel setting;
    private javax.swing.JLabel tampilFoto;
    private javax.swing.JLabel txtDashboard;
    // End of variables declaration//GEN-END:variables
}
